### ISSUE TITLE
Marketplace still version 1.0.1

### ISSUE THREAD

**Issue by RedMarlin** [joakimbo/user-permissions-plugin#3]
I think you forgot to update October marketplace package it still features version 1.0.1

**Comment by joakimbo** [comment]
Hi, @RedMarlin 
Don't worry I have not forgotten to.
The reason is partly that I have been quite busy for a while now but also that I have simply opted not to push update the marketplace until a point where I could make one single update that covers more ground. However, since you brought this up I might take the time to finalize some changes and update the marketplace version this weekend.
