### ISSUE TITLE
Add 'can' alias

### ISSUE THREAD

**Issue by frthjf** [joakimbo/user-permissions-plugin#5]
I think it would be nice to have a shorthand ``can`` alias for the ``hasUserPermission`` method which I think would be a bit more natural and concise (``$user->can('create-post')``). I'd be happy to create a PR.

**Comment by joakimbo** [comment]
Hi, @frthjf while I am not against this since I understand that it is tedious having to write the entire method name "hasUserPermission" every time one wants to make a check I do have some concerns.
- What would happen if this plugin and another plugin registers a "can" alias on the user model, with totally different implementations in mind? I would assume this would create an incompatibility between these two plugins, perhaps a small chance but still not acceptable from my point of view.
- What if the permission is not a verb? If one would only want to approve Batman into his cave one would probably not say that he "can('isBatman')", should we have to register several aliases to accommodate this?

**Comment by frthjf** [comment]
Hi @joakimbo, thanks for your quick reply. I can see your concerns. ``hasUserPermission`` is less likely to clash if the user happens to install two different permission extensions at the same the time. A clash wouldn't create an incompatibility though, because the dynamic method would just [be overwritten by one or the other plugin](https://github.com/octobercms/library/blob/4bda08c826fc3ac1efba32fa8799d25ced14191f/src/Extension/ExtendableTrait.php#L169). So ``$user->can`` would just call into the other plugins method which is probably acceptable or even expected behaviour. 
For the other point, I agree that the ``can`` alias wouldn't make much sense in non-verbal use. In that case it would just be better to not use the alias but stick with ``hasUserPermission``. 

One other option would be to make the [method name binding](https://github.com/joakimbo/user-permissions-plugin/blob/e3bdbc04e06f1a28fccaf477493e92961ed23b18/Plugin.php#L153) configurable by the developer by changing the hard-coded name into
```php
$model->addDynamicMethod(Config::get('jbonnydev.userpermissions::permissionMethodName', 'hasUserPermission'), ...)
```
That way, the default name can be changed using [a configuration file](https://octobercms.com/docs/plugin/settings#file-configuration). This would also be helpful in case of a name clash, because you could adjust to a conflict free name.

**Comment by joakimbo** [comment]
@frthjf This seemed like a easy solution to this issue so I went ahead and implemented it.

Thanks for the idea.

**Comment by frthjf** [comment]
Thanks @joakimbo , that's great!
